import type { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
  title: '사내정보관리시스템',
  description: 'Generated by create MostX',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head>
        {/* <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css" /> */}
      </head>
      <body>{children}</body>
    </html>
  )
}